import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../models/report_model.dart';

class PdfReportService {
  static final PdfReportService _instance = PdfReportService._internal();
  factory PdfReportService() => _instance;
  PdfReportService._internal();

  // Company colors
  static const PdfColor primaryBlue = PdfColor.fromInt(0xFF1976D2);
  static const PdfColor lightBlue = PdfColor.fromInt(0xFF5DADE2);
  static const PdfColor darkGray = PdfColor.fromInt(0xFF2C3E50);
  static const PdfColor lightGray = PdfColor.fromInt(0xFFF5F7FA);
  static const PdfColor green = PdfColor.fromInt(0xFF27AE60);
  static const PdfColor red = PdfColor.fromInt(0xFFE74C3C);
  static const PdfColor orange = PdfColor.fromInt(0xFFF39C12);

  /// Generate Overview Report PDF
  Future<File> generateOverviewPDF({
    required ReportOverview overview,
    required String dateRange,
    required String userName,
    String? divisionName,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormatter = DateFormat('dd MMMM yyyy');
    final timeFormatter = DateFormat('HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(
          title: 'Visit Overview Report',
          userName: userName,
          divisionName: divisionName,
        ),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // Report Info
          _buildSectionTitle('Report Information'),
          pw.SizedBox(height: 10),
          _buildInfoRow('Period:', dateRange),
          _buildInfoRow('Generated:', '${dateFormatter.format(now)} at ${timeFormatter.format(now)}'),
          _buildInfoRow('Generated by:', userName),
          if (divisionName != null) _buildInfoRow('Division:', divisionName),
          
          pw.SizedBox(height: 20),
          pw.Divider(color: lightGray, thickness: 2),
          pw.SizedBox(height: 20),

          // Summary Statistics
          _buildSectionTitle('Summary Statistics'),
          pw.SizedBox(height: 15),
          
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildStatCard('Total Visits', overview.totalVisits.toString(), primaryBlue),
              _buildStatCard('Total Outlets', overview.totalOutlets.toString(), lightBlue),
            ],
          ),
          
          pw.SizedBox(height: 20),

          // Response Summary
          _buildSectionTitle('Response Summary'),
          pw.SizedBox(height: 15),
          
          pw.Container(
            padding: const pw.EdgeInsets.all(15),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: lightGray, width: 1),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              children: [
                _buildResponseRow('OK (Correct)', overview.okCount, overview.okPercentage, green),
                pw.SizedBox(height: 10),
                _buildResponseRow('NOK (Issues Found)', overview.nokCount, overview.nokPercentage, red),
                pw.SizedBox(height: 10),
                _buildResponseRow('N/A (Not Applicable)', overview.naCount, 
                  overview.totalResponses > 0 
                    ? (overview.naCount / overview.totalResponses * 100) 
                    : 0.0, 
                  orange),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Recent Visits
          if (overview.recentVisits.isNotEmpty) ...[
            _buildSectionTitle('Recent Visits'),
            pw.SizedBox(height: 15),
            _buildRecentVisitsTable(overview.recentVisits),
          ],
        ],
      ),
    );

    return _savePDF(pdf, 'Overview_Report_${now.millisecondsSinceEpoch}.pdf');
  }

  /// Generate Outlet Report PDF
  Future<File> generateOutletPDF({
    required List<OutletReport> outlets,
    required String dateRange,
    required String userName,
    String? divisionName,
    String? filterStatus,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormatter = DateFormat('dd MMMM yyyy');
    final timeFormatter = DateFormat('HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(
          title: 'Outlet Performance Report',
          userName: userName,
          divisionName: divisionName,
        ),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // Report Info
          _buildSectionTitle('Report Information'),
          pw.SizedBox(height: 10),
          _buildInfoRow('Period:', dateRange),
          _buildInfoRow('Generated:', '${dateFormatter.format(now)} at ${timeFormatter.format(now)}'),
          _buildInfoRow('Generated by:', userName),
          if (divisionName != null) _buildInfoRow('Division:', divisionName),
          if (filterStatus != null) _buildInfoRow('Filter:', filterStatus),
          _buildInfoRow('Total Outlets:', outlets.length.toString()),
          
          pw.SizedBox(height: 20),
          pw.Divider(color: lightGray, thickness: 2),
          pw.SizedBox(height: 20),

          // Outlets List
          _buildSectionTitle('Outlet Performance'),
          pw.SizedBox(height: 15),
          
          ...outlets.map((outlet) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildOutletCard(outlet),
              pw.SizedBox(height: 15),
            ],
          )),
        ],
      ),
    );

    return _savePDF(pdf, 'Outlet_Report_${now.millisecondsSinceEpoch}.pdf');
  }

  /// Build PDF Header with Logo
  pw.Widget _buildHeader({
    required String title,
    required String userName,
    String? divisionName,
  }) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 20),
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: primaryBlue,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'T&D System',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                title,
                style: const pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 14,
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                userName,
                style: const pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 12,
                ),
              ),
              if (divisionName != null)
                pw.Text(
                  divisionName,
                  style: pw.TextStyle(
                    color: PdfColors.white.shade(0.8),
                    fontSize: 10,
                  ),
                ),
            ],
          ),
        ],
      ),
    );
  }

  /// Build PDF Footer with Page Number
  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 20),
      padding: const pw.EdgeInsets.symmetric(vertical: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: lightGray, width: 1)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'T&D System - Training & Development',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey),
          ),
        ],
      ),
    );
  }

  /// Build Section Title
  pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 16,
        fontWeight: pw.FontWeight.bold,
        color: darkGray,
      ),
    );
  }

  /// Build Info Row
  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
                color: darkGray,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value,
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        ],
      ),
    );
  }

  /// Build Stat Card
  pw.Widget _buildStatCard(String label, String value, PdfColor color) {
    return pw.Container(
      width: 220,
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: color,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 28,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            label,
            style: const pw.TextStyle(
              fontSize: 12,
              color: PdfColors.white,
            ),
          ),
        ],
      ),
    );
  }

  /// Build Response Row
  pw.Widget _buildResponseRow(String label, int count, double percentage, PdfColor color) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Row(
          children: [
            pw.Container(
              width: 12,
              height: 12,
              decoration: pw.BoxDecoration(
                color: color,
                shape: pw.BoxShape.circle,
              ),
            ),
            pw.SizedBox(width: 10),
            pw.Text(
              label,
              style: const pw.TextStyle(fontSize: 11),
            ),
          ],
        ),
        pw.Row(
          children: [
            pw.Text(
              '$count items',
              style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(width: 15),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: pw.BoxDecoration(
                color: color,
                borderRadius: pw.BorderRadius.circular(10),
              ),
              child: pw.Text(
                '${percentage.toStringAsFixed(1)}%',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.white,
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  /// Build Recent Visits Table
  pw.Widget _buildRecentVisitsTable(List<RecentVisit> visits) {
    return pw.Table(
      border: pw.TableBorder.all(color: lightGray, width: 1),
      children: [
        // Header
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: lightGray),
          children: [
            _buildTableCell('Outlet', isHeader: true),
            _buildTableCell('Visit Date', isHeader: true),
            _buildTableCell('Status', isHeader: true),
            _buildTableCell('OK %', isHeader: true),
          ],
        ),
        // Data rows
        ...visits.take(10).map((visit) => pw.TableRow(
          children: [
            _buildTableCell(visit.outletName),
            _buildTableCell(visit.visitDate),
            _buildTableCell(visit.status),
            _buildTableCell(
              '${visit.okPercentage.toStringAsFixed(1)}%',
              color: visit.okPercentage >= 85 ? green : (visit.okPercentage >= 70 ? orange : red),
            ),
          ],
        )),
      ],
    );
  }

  /// Build Table Cell
  pw.Widget _buildTableCell(String text, {bool isHeader = false, PdfColor? color}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: color,
        ),
      ),
    );
  }

  /// Build Outlet Card
  pw.Widget _buildOutletCard(OutletReport outlet) {
    final statusColor = outlet.status == 'Good' ? green : (outlet.status == 'Warning' ? orange : red);
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: lightGray, width: 1),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Outlet Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Expanded(
                child: pw.Text(
                  outlet.outletName,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    color: darkGray,
                  ),
                ),
              ),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: pw.BoxDecoration(
                  color: statusColor,
                  borderRadius: pw.BorderRadius.circular(12),
                ),
                child: pw.Text(
                  outlet.status,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 8),
          pw.Text(
            outlet.city ?? 'N/A',
            style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
          
          pw.SizedBox(height: 12),
          pw.Divider(color: lightGray),
          pw.SizedBox(height: 8),
          
          // Statistics
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildOutletStat('Visits', outlet.totalVisits.toString()),
              _buildOutletStat('OK', '${outlet.okPercentage.toStringAsFixed(1)}%', color: green),
              _buildOutletStat('NOK', '${outlet.nokPercentage.toStringAsFixed(1)}%', color: red),
              _buildOutletStat('N/A', '${outlet.naCount}', color: orange),
            ],
          ),
          
          // Top NOK Issues
          if (outlet.topNokIssues.isNotEmpty) ...[
            pw.SizedBox(height: 12),
            pw.Divider(color: lightGray),
            pw.SizedBox(height: 8),
            pw.Text(
              'Top Issues:',
              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 5),
            ...outlet.topNokIssues.take(3).map((issue) => pw.Padding(
              padding: const pw.EdgeInsets.only(left: 10, top: 3),
              child: pw.Row(
                children: [
                  pw.Text('•', style: const pw.TextStyle(fontSize: 10)),
                  pw.SizedBox(width: 5),
                  pw.Expanded(
                    child: pw.Text(
                      issue.point,
                      style: const pw.TextStyle(fontSize: 9),
                    ),
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                    decoration: pw.BoxDecoration(
                      color: red,
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.Text(
                      '${issue.frequency}x',
                      style: const pw.TextStyle(
                        fontSize: 8,
                        color: PdfColors.white,
                      ),
                    ),
                  ),
                ],
              ),
            )),
          ],
        ],
      ),
    );
  }

  /// Build Outlet Stat
  pw.Widget _buildOutletStat(String label, String value, {PdfColor? color}) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: color ?? darkGray,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          label,
          style: pw.TextStyle(fontSize: 8, color: PdfColors.grey),
        ),
      ],
    );
  }

  /// Save PDF to device storage
  Future<File> _savePDF(pw.Document pdf, String fileName) async {
    final output = await getApplicationDocumentsDirectory();
    final file = File('${output.path}/$fileName');
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
